# This file was generated by GoReleaser. DO NOT EDIT.
class Fscripts < Formula
  desc "Eff scripts"
  homepage "https://github.com/Freshly/fscripts"
  version "0.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Freshly/fscripts/releases/download/v0.0.0/fscripts_0.0.0_Darwin_x86_64.tar.gz"
    sha256 "9b2051b7c111fe6672f09f279084b74ce582d77e93c90e35ca7d6ed1b40db51c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Freshly/fscripts/releases/download/v0.0.0/fscripts_0.0.0_Linux_x86_64.tar.gz"
      sha256 "2c7110c1a7ab8cbe488fb4df30389c3cb75f2bf1c2bc561d3ce9a70bd65c6afd"
    end
  end

  def install
    bin.install "fscripts"
  end

  test do
    system "#{bin}/fscripts -v"
  end
end
