# This file was generated by GoReleaser. DO NOT EDIT.
class Tuber < Formula
  desc "🥔"
  homepage "https://github.com/Freshly/tuber"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Freshly/tuber/releases/download/v1.0.0/tuber_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "ca06a153f2467d690507489e0ae4f55964d3945a105d2db163d033127dd109d1"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Freshly/tuber/releases/download/v1.0.0/tuber_1.0.0_Linux_x86_64.tar.gz"
    sha256 "170aa7b2acd7d56d2287df30b6c12a06d9c293ff191973141c2ee48421f0e010"
  end

  def install
    bin.install "tuber"
  end

  test do
    system "#{bin}/tuber -v"
  end
end
