# This file was generated by GoReleaser. DO NOT EDIT.
class Tuber < Formula
  desc "🥔"
  homepage "https://github.com/Freshly/tuber"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Freshly/tuber/releases/download/v0.1.1/tuber_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "d3daf6f6dcaba9ee0706fb2a751d110bab68052c3abb18aa4899fd0885d19ee4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Freshly/tuber/releases/download/v0.1.1/tuber_0.1.1_Linux_x86_64.tar.gz"
      sha256 "f728bc3b7d83c81f94f3256adaf6fd03df3f07abe0900e662f08a7ca73ce49f8"
    end
  end
  
  depends_on "kubernetes-cli"

  def install
    bin.install "tuber"
  end

  test do
    system "#{bin}/tuber -v"
  end
end
